Repository girlscriptjaipur/girlscriptjaipur.github.io, pull requests merged in 2019-06, with the labels that each got.

#82 photos and links added
  images/Karina.jpg
  images/Saksham.jpeg
  images/Tushar.jpg
  index.html
Labels: good first issue

#83 links added
  index.html
Labels: good first issue

#84 closes #15
  index.html
Labels: good first issue

#88 Content changed
  meetup-ds-amity.html
Labels: enhancement, good first issue

#90 New CTM added
  images/rashi.jpeg
  index.html
Labels: enhancement

#93 Subscribe button and input corrected
  gdtc-details.html
Labels: enhancement

#94 GDTC new page added
  gdtcdetails.html
Labels: enhancement

#104 Pic added
  gdtc.html
  images/IMG_20181225_175554_Bokeh (1).jpg
  images/shutterstock_459867970-1392x742.jpg
  index.html
Labels: enhancement
